/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Opt(IDL.Text),
  'updatedTime' : IDL.Int,
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'createdTime' : IDL.Int,
  'quantityOnHand' : IDL.Nat,
  'unitPrice' : IDL.Nat,
  'unitCost' : IDL.Opt(IDL.Nat),
});
export const DashboardSummary = IDL.Record({
  'totalProducts' : IDL.Nat,
  'todaysSalesAmount' : IDL.Nat,
  'lowStockProducts' : IDL.Vec(Product),
});
export const SaleLineItem = IDL.Record({
  'unitPriceAtSale' : IDL.Nat,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], []),
  'recordSale' : IDL.Func(
      [IDL.Vec(SaleLineItem), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Opt(IDL.Text),
    'updatedTime' : IDL.Int,
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'createdTime' : IDL.Int,
    'quantityOnHand' : IDL.Nat,
    'unitPrice' : IDL.Nat,
    'unitCost' : IDL.Opt(IDL.Nat),
  });
  const DashboardSummary = IDL.Record({
    'totalProducts' : IDL.Nat,
    'todaysSalesAmount' : IDL.Nat,
    'lowStockProducts' : IDL.Vec(Product),
  });
  const SaleLineItem = IDL.Record({
    'unitPriceAtSale' : IDL.Nat,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  
  return IDL.Service({
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], []),
    'recordSale' : IDL.Func(
        [IDL.Vec(SaleLineItem), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };