/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardSummary {
  'totalProducts' : bigint,
  'todaysSalesAmount' : bigint,
  'lowStockProducts' : Array<Product>,
}
export interface Product {
  'id' : bigint,
  'sku' : [] | [string],
  'updatedTime' : bigint,
  'name' : string,
  'description' : [] | [string],
  'createdTime' : bigint,
  'quantityOnHand' : bigint,
  'unitPrice' : bigint,
  'unitCost' : [] | [bigint],
}
export interface SaleLineItem {
  'unitPriceAtSale' : bigint,
  'productId' : bigint,
  'quantity' : bigint,
}
export interface _SERVICE {
  'createProduct' : ActorMethod<
    [string, [] | [string], [] | [string], bigint, [] | [bigint], bigint],
    bigint
  >,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'recordSale' : ActorMethod<[Array<SaleLineItem>, [] | [string]], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];